export const amenities = [
  {
      id:1,
      code:'WIFI',
      name:'Wifi',
      isChecked: false,
      price: '2314',
  },
  {
      id:2,
      code:'FITNESS_CENTER',
      name:'Fitness Center',
      isChecked: false,
      price: '2315',
  },
  {
      id:3,
      code:'SWIMMING_POOL',
      name:'Swimming Pool',
      isChecked: false,
      price: '2316',
  },
  {
      id:4,
      code:'AIRPORT_SHUTTLE',
      name:'Airport Shuttle',
      isChecked: false,
      price: '2317',
  },
  {
      id:5,
      code:'RESTAURANT',
      name:'Restaurant',
      isChecked: false,
      price: '2318',
  },
  {
      id:6,
      code:'PARKING',
      name:'Parking',
      isChecked: false,
      price: '2319',
  },
  {
      id:7,
      code:'SPA',
      name:'Spa',
      isChecked: false,
      price: '2320',
  },
  {
      id:8,
      code:'AIR_CONDITIONING',
      name:'Air Conditioning',
      isChecked: false,
      price: '2321',
  },
  {
      id:9,
      code:'PETS_ALLOWED',
      name:'Pets Allowed',
      isChecked: false,
      price: '2322',
  },
  {
      id:10,
      code:'BUSINESS_CENTER',
      name:'Business Center',
      isChecked: false,
      price: '2323',
  },
  {
      id:11,
      code:'DISABLED_FACILITIES',
      name:'Disabled Facilities',
      isChecked: false,
      price: '2324',
  },
  {
      id:12,
      code:'MEETING_ROOMS',
      name:'Meeting Rooms',
      isChecked: false,
      price: '2000',
  },
  {
      id:13,
      code:'NO_KID_ALLOWED',
      name:'No Kid Allowed',
      isChecked: false,
      price: '2001',
  },
  {
      id:14,
      code:'TENNIS',
      name:'Tennis',
      isChecked: false,
      price: '2002',
  },
  {
      id:15,
      code:'GOLF',
      name:'Golf',
      isChecked: false,
      price: '2003',
  },
  {
      id:16,
      code:'KITCHEN',
      name:'Kitchen',
      isChecked: false,
      price: '2004',
  },
  {
      id:17,
      code:'ANIMAL_WATCHING',
      name:'Animal Watching',
      isChecked: false,
      price: '2006',
  },
  {
      id:18,
      code:'BABY-SITTING',
      name:'Baby Sitting',
      isChecked: false,
      price: '2007',
  },
  {
      id:19,
      code:'BEACH',
      name:'Beach',
      isChecked: false,
      price: '2008',
  },
  {
      id:20,
      code:'CASINO',
      name:'Casino',
      isChecked: false,
      price: '2009',
  },
  {
      id:21,
      code:'JACUZZI',
      name:'Jacuzzi',
      isChecked: false,
      price: '2010',
  },
  {
      id:22,
      code:'SAUNA',
      name:'Sauna',
      isChecked: false,
      price: '2011',
  },
  {
      id:23,
      code:'SOLARIUM',
      name:'Solarium',
      isChecked: false,
      price: '2012',
  },
  {
      id:24,
      code:'MASSAGE',
      name:'Message',
      isChecked: false,
      price: '2013',
  },
  {
      id:25,
      code:'VALET_PARKING',
      name:'Valet Parking',
      isChecked: false,
      price: '2014',
  },
  {
      id:26,
      code:'BAR',
      name:'Bar',
      isChecked: false,
      price: '2015',
  },
  {
      id:27,
      code:'KIDS_WELCOME',
      name:'Kids Welcome',
      isChecked: false,
      price: '2016',
  },
  {
      id:28,
      code:'NO_PORN_FILMS',
      name:'No Porn Films',
      isChecked: false,
      price: '2017',
  },
  {
      id:29,
      code:'MINIBAR',
      name:'Minibar',
      isChecked: false,
      price: '2018',
  },
  {
      id:30,
      code:'TELEVISION',
      name:'Television',
      isChecked: false,
      price: '2019',
  },
  {
      id:31,
      code:'WI-FI_IN_ROOM',
      name:'Wifi In Room',
      isChecked: false,
      price: '2020',
  },
  {
      id:32,
      code:'ROOM_SERVICE',
      name:'Room Service',
      isChecked: false,
      price: '2021',
  },
  {
      id:33,
      code:'GUARDED_PARKG',
      name:'Guarded Parking',
      isChecked: false,
      price: '2021',
  },
  {
      id:34,
      code:'SERV_SPEC_MENU',
      name:'Serv Spec Menu',
      isChecked: false,
      price: '2021',
  },
]